name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  spotless:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - run: chmod +x gradlew
      - run: ./gradlew spotlessCheck

  build:
    name: Build
    needs: spotless
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACTIONS_PAT }}
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - run: chmod +x gradlew
      - run: ./gradlew build -x test
